spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trades
    username: ${DB_USER:arbitrage}
    password: ${DB_PASS:yyQjYDvhKRsLphXl@4567}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

arb:
  order-size-usd: 100000
  edge-threshold: 0.00025
  max-open-orders: 1
  scan-interval-ms: 1000
  trade-cooldown-ms: 10000
  broadcast-interval-ms: 1000

kraken:
  ws-url: wss://ws.kraken.com/v2
  api-key: CuUXlJ6bnW9iHEEiHvJiJ+1e+vkEPj7igCAbqM4UyOI4NqvCel+2aI4f
  #${KRAKEN_API_KEY:}
  api-secret: 2+xhOGxgWPDLgDyenaoOkabb79c0sTtu02FNPIpphOKZzZe209Le+NKYDPm5pfLMHy66DCnA5QeuWGXqSawzyA==
  #${KRAKEN_API_SECRET:}
  position-cache-ttl-ms: 2000

currency:
  feed-url: ${CURRENCY_FEED_URL:ws://136.244.86.163:8080/api/ws/global}

alert:
  email-from: ${ALERT_EMAIL_FROM:}
  email-password: ${ALERT_EMAIL_PASS:}
  email-to: ${ALERT_EMAIL_TO:}

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:yyQjYDvhKRsLphXl@}
